### ISSUE TITLE
Laravel Profiler is Blank

### ISSUE THREAD

**Issue by kimchirichie** [jkocik/laravel-profiler#9]
I've actually been able to use this package on my current project a few months ago - no problem.

Recently turned the profiler up to do some optimizations on my query, but nothing seems to come thru the profiler client.

Here is my current setup/situation:
- environment variable PROFILER_ENABLED=true
- started my local server `php artisan serve`
- started profiler server `php artisan pro:serve` (also tried with npm run ps)
- started profiler client `php artisan pro:cli` (also tried with npm run pc)
- profiler.php is all default
- Laravel Profiler client [shows up](https://puu.sh/HlIli/245c17b51a.png) on browser 
- refresh localhost:8000 to find the profiler client empty.

Additional information
- `php artisan pro:status` gives error: BroadcastingProcessor did not report connection status, connection status is unknown
- logger spits out:

> local.ERROR: GuzzleHttp\Exception\InvalidArgumentException: json_encode error: Inf and NaN cannot be JSON encoded in /Users/kimchirichie/myproject/vendor/guzzlehttp/guzzle/src/functions.php:328
> Stack trace:
> #0 /Users/brainfogz/myproject/vendor/guzzlehttp/guzzle/src/Client.php(397): GuzzleHttp\json_encode(Array)
> #1 /Users/brainfogz/myproject/vendor/guzzlehttp/guzzle/src/Client.php(346): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array)
> #2 /Users/brainfogz/myproject/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
> #3 /Users/brainfogz/myproject/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
> #4 /Users/brainfogz/myproject/vendor/jkocik/laravel-profiler/src/Processors/BroadcastingProcessor.php(57): GuzzleHttp\Client->request('POST', 'http://localhos...', Array)
> #5 /Users/brainfogz/myproject/vendor/jkocik/laravel-profiler/src/Processors/BroadcastingProcessor.php(42): JKocik\Laravel\Profiler\Processors\BroadcastingProcessor->broadcast(Object(JKocik\Laravel\Profiler\LaravelDataTracker), 'http://localhos...')
> #6 /Users/brainfogz/myproject/vendor/jkocik/laravel-profiler/src/LaravelDataProcessor.php(58): JKocik\Laravel\Profiler\Processors\BroadcastingProcessor->process(Object(JKocik\Laravel\Profiler\LaravelDataTracker))
> #7 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): JKocik\Laravel\Profiler\LaravelDataProcessor->JKocik\Laravel\Profiler\{closure}('JKocik\\Laravel\\...', 0)
> #8 /Users/brainfogz/myproject/vendor/jkocik/laravel-profiler/src/LaravelDataProcessor.php(62): Illuminate\Support\Collection->each(Object(Closure))
> #9 /Users/brainfogz/myproject/vendor/jkocik/laravel-profiler/src/LaravelProfiler.php(96): JKocik\Laravel\Profiler\LaravelDataProcessor->process(Object(JKocik\Laravel\Profiler\LaravelDataTracker))
> #10 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): JKocik\Laravel\Profiler\LaravelProfiler->JKocik\Laravel\Profiler\{closure}()
> #11 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #12 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
> #13 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
> #14 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
> #15 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1091): Illuminate\Container\Container->call(Object(Closure))
> #16 /Users/brainfogz/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(148): Illuminate\Foundation\Application->terminate()
> #17 /Users/brainfogz/myproject/artisan(51): Illuminate\Foundation\Console\Kernel->terminate(Object(Symfony\Component\Console\Input\ArgvInput), 0)
> #18 {main}

what more can i do to debug this situation?

**Comment by internetfett** [comment]
I'm not seeing anything either. 'List is Empty' with Laravel 7x.

**Comment by jkocik** [comment]
Hi, I can not reproduce it. You can pull latest version and comment out all trackers (to turn them off) in config file. If that works you can turn them on one by one to figure out which of them makes the issue.

**Comment by victor-priceputu** [comment]
I have the same issue, I followed @jkocik's advice and the ConfigTracker is the one that breaks it for me.

jkocik/laravel-profiler v2.0.3
laravel/framework v8.48.1

**Comment by jomonkj** [comment]
if your using vhost 
config `server_http.address` or add WebSocket Server url by clicking power button on right top bar.

**Comment by Nereb-Nanok** [comment]
hello 
please , when I enter:  php artisan pro:cli
i get this error: 
Starting Profiler Client ...
'node_modules' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

help me

**Comment by xtrcode** [comment]
For me it was a misconfiguration of nginx and php:

nginx.conf:
`client_body_buffer_size 256m;`
`client_max_body_size 64m;`

php.ini:
`post_max_size = 64M`

Error messages:
`[error] 307#307: *9 FastCGI sent in stderr: "PHP message: PHP Warning:  Unknown: POST Content-Length of 22612811 bytes exceeds the limit of 8388608 bytes in Unknown on line 0`

`[warn] 307#307: *5 an upstream response is buffered to a temporary file /var/lib/nginx/fastcgi/2/00/0000000002 while reading upstream, client: 172.30.0.1, server: localhost, request: "POST /:8099 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "192.168.2.187"`
